### ISSUE TITLE
FYI: had to force push master

### ISSUE THREAD

**Issue by janl** [hoodiehq/hoodie-plugin-template#1]
Heya, I worked on a new plugin based off this and made a flub not changing the git origin URL and accidentally committed to this repo instead of the new one. I git reset the master branch locally to the original state and then force pushed to here so it looks like nothing has happened about two minutes later. This just to let you know.

**Comment by varjmes** [comment]
Thanks for letting us know @janl. I think I will close this as it is a year later and I'm sure it has been seen by now! :tada:

**Comment by janl** [comment]
Thanks :D
